export const LOCATIONS = {
    Antalya: {
        'Akseki': ['Merkez', 'Bademli', 'Cevizli'],
        'Aksu': ['Atatürk', 'Barbaros', 'Çalkaya', 'Güzelyurt', 'Konak', 'Macun', 'Pınarlı', 'Soğucak'],
        'Alanya': ['Avsallar', 'Cikcilli', 'Çıplaklı', 'Demirtaş', 'Emişbeleni', 'Kargıcak', 'Kestel', 'Konaklı', 'Mahmutlar', 'Oba', 'Okurcalar', 'Payallar', 'Tosmur', 'Türkler'],
        'Demre': ['Alakent', 'Beymelek', 'Büyükkum', 'Gökyazı', 'Karabucak', 'Kayaaltı'],
        'Döşemealtı': ['Altınkale', 'Bahçeyaka', 'Çıplaklı', 'Düzlerçamı', 'Yeşilbayır', 'Yeniköy', 'Tomalar', 'Termessos Bulvarı', 'Kovanlık'],
        'Elmalı': ['Karyağdı', 'Toklular', 'Yeni', 'İplik Pazarı'],
        'Finike': ['Eski', 'Hasyurt', 'İskele', 'Sahilkent', 'Turunçova', 'Yeşilyurt'],
        'Gazipaşa': ['Aydın', 'Bakılar', 'Cumhuriyet', 'Gazi', 'İstiklal', 'Koru', 'Pazarcı'],
        'Gündoğmuş': ['Fatih', 'Rasih Kaplan', 'Özügür'],
        'İbradı': ['Aşağı', 'Yukarı'],
        'Kaş': ['Andifli', 'Gömbe', 'Kalkan', 'Kınık', 'Ova', 'Yeşilköy'],
        'Kemer': ['Arslanbucak', 'Beldibi', 'Çamyuva', 'Göynük', 'Kiriş', 'Tekirova', 'Yeni'],
        'Kepez': ['Ahatlı', 'Altınova', 'Atatürk', 'Ayanoğlu', 'Barış', 'Çankaya', 'Demirel', 'Düdenbaşı', 'Emek', 'Erenköy', 'Esentepe', 'Fabrikalar', 'Fevzi Çakmak', 'Gazi', 'Göçerler', 'Gülveren', 'Habibler', 'Hüsnü Karakaş', 'Kanal', 'Karşıyaka', 'Kazım Karabekir', 'Kültür', 'Kütükçü', 'Kuzeyyaka', 'Mehmet Akif Ersoy', 'Menderes', 'Özgürlük', 'Santral', 'Sütçüler', 'Şafak', 'Teomanpaşa', 'Ulus', 'Ünsal', 'Varsak', 'Yavuz Selim', 'Yeni', 'Yeni Doğan', 'Yeşiltepe', 'Yeşilyurt', 'Yükseliş', 'Zafer', 'Zeytinlik'],
        'Konyaaltı': ['Arapsuyu', 'Aşağıkaraman', 'Aydınlık', 'Bahtılı', 'Çağlarca', 'Çakırlar', 'Demircikara', 'Doyran', 'Geyikbayırı', 'Gürsu', 'Hacısekililer', 'Hisarçandır', 'Hurma', 'Karatepe', 'Kır', 'Kuruçay', 'Kuşkavağı', 'Liman', 'Molla Yusuf', 'Öğretmenevleri', 'Pınarbaşı', 'Sarısu', 'Siteler', 'Toros', 'Uncalı', 'Yarbaşçandır', 'Yeni', 'Zümrüt'],
        'Korkuteli': ['Alaaddin', 'Aşağıpazar', 'Kiremitli', 'Uzunoluk', 'Yeni'],
        'Kumluca': ['Adrasan', 'Bağlık', 'Beykonak', 'Cumhuriyet', 'Eski Cami', 'Göksu', 'Hacıveliler', 'Karşıyaka', 'Kasapçayırı', 'Mavikent', 'Merkez', 'Narenciye', 'Sarıcasu', 'Temel Eğitim', 'Yeni'],
        'Manavgat': ['Aşağı Hisar', 'Aşağı Pazarcı', 'Aydınevler', 'Bahçelievler', 'Çağlayan', 'Emek', 'Eski Hisar', 'Ilıca', 'Kasaplar', 'Kavaklı', 'Milli Egemenlik', 'Mimarsinan', 'Örnek', 'Salkım Evler', 'Sanayi', 'Sarılar', 'Side', 'Şelale', 'Ulukapı', 'Yayla', 'Yukarı Hisar', 'Yukarı Pazarcı'],
        'Muratpaşa': ['Altındağ', 'Bahçelievler', 'Balbey', 'Barbaros', 'Bayındır', 'Çağlayan', 'Çaybaşı', 'Cumhuriyet', 'Demircikara', 'Deniz', 'Doğuyaka', 'Dutlubahçe', 'Elmalı', 'Ermenek', 'Etiler', 'Fener', 'Gebizli', 'Gençlik', 'Güvenlik', 'Güzelibağ', 'Güzeloba', 'Güzeloluk', 'Haşimişcan', 'Kışla', 'Kırcami', 'Kızılarık', 'Kızılsaray', 'Kızılırmak', 'Konuksever', 'Mehmetçik', 'Meltem', 'Memurevleri', 'Meydankavağı', 'Muratpaşa', 'Sedir', 'Selçuk', 'Sinan', 'Soğuksu', 'Şirinyalı', 'Tahılpazarı', 'Tarım', 'Topçular', 'Tuzcular', 'Üçgen', 'Varlık', 'Yenigün', 'Yenigöl', 'Yüksekalan', 'Yeşilbahçe', 'Yeşildere', 'Yeşilova', 'Yıldız', 'Zerdalilik', 'Zümrütova'],
        'Serik': ['Akçaalan', 'Belek', 'Boğazkent', 'Cumali', 'Gedik', 'Kadriye', 'Karadayı', 'Kökez', 'Kürüş', 'Merkez', 'Orta', 'Yeni']
    },
    Isparta: {
        'Aksu': ['Merkez', 'Pazarcık', 'Yaka'],
        'Atabey': ['Altunba', 'Yeni', 'Müftü'],
        'Eğirdir': ['Altınkum', 'Bağlar', 'Cami', 'Hacışeyh', 'İstasyon', 'Kızılçubuk', 'Kubbeli', 'Menderes', 'Pınar Pazarı', 'Poyraz', 'Sanayi', 'Seydim', 'Yazla', 'Yeni', 'Yeşilada'],
        'Gelendost': ['Aşağı', 'Yukarı', 'Bahçelievler'],
        'Gönen': ['Cami', 'Göletevleri'],
        'Keçiborlu': ['Aşağı', 'Orta', 'Tuzla', 'Yenice'],
        'Merkez': ['Anadolu', 'Bahçelievler', 'Batıkent', 'Binbirevler', 'Çünür', 'Davraz', 'Fatih', 'Hızırbey', 'İstiklal', 'Karaağaç', 'Kepeci', 'Mehmet Tönge', 'Modernevler', 'Piri Mehmet', 'Sanayi', 'Yedişehitler', 'Zafer'],
        'Senirkent': ['Hamidiye', 'Cumhuriyet', 'Turgutlar'],
        'Sütçüler': ['Belen', 'Çamyazı', 'Yeşilyurt'],
        'Şarkikaraağaç': ['Aşağı Kale', 'Orta Kale', 'Yukarı Kale'],
        'Uluborlu': ['Topraklık', 'Selçuklu'],
        'Yalvaç': ['Abacılar', 'Bağlarbaşı', 'Debbaglar', 'Eski', 'Fatih', 'Görgü Cami', 'Gülistan', 'Kaş Cami', 'Kaş Hacıbey', 'Kızılca', 'Müderris', 'Pazar Aşağı', 'Pazar Yukarı', 'Salur', 'Sanayi', 'Saray', 'Sofular', 'Zafer'],
        'Yenişarbademli': ['Pınarbaşı']
    },
    Burdur: {
        'Ağlasun': ['Bala', 'Kıraç', 'Sakarya'],
        'Altınyayla': ['Gülpınar'],
        'Bucak': ['Alaattin', 'Atatürk', 'Cami', 'Çamlıca', 'Çavuşlar', 'Fatih', 'Konak', 'Mehmet Akif', 'Mimar Sinan', 'Oğuzhan', 'Onaç', 'Pazar', 'Sanayi', 'Yeni', 'Yörükler', 'Yunus Emre'],
        'Çavdır': ['Pazar'],
        'Çeltikçi': ['Konak'],
        'Gölhisar': ['Armutlu', 'Çeşme', 'Fatih', 'Konak', 'Merkez Cami', 'Pazar', 'Ulucami'],
        'Karamanlı': ['Barbaros', 'Çamlık', 'Eşeler', 'Fatih', 'Pazar', 'Zafer'],
        'Kemer': ['Yeni'],
        'Merkez': ['Armağan İlci', 'Atatürk', 'Aydınlıkevler', 'Bağlar', 'Bahçelievler', 'Berberoğlu', 'Bozkurt', 'Burç', 'Cemil', 'Çeşmedamı', 'Dere', 'Emek', 'Fevzi Çakmak', 'Hızır İlyas', 'İnönü', 'Karaburç', 'Karasenir', 'Kışla', 'Konak', 'Menderes', 'Necatibey', 'Özgür', 'Pazar', 'Recep', 'Sakarya', 'Sinan', 'Şirinevler', 'Tepe', 'Üçdibek', 'Yeni', 'Yenice', 'Zafer'],
        'Tefenni': ['Esentepe', 'Eşeler', 'Fatih', 'Kır', 'Pazar', 'Yokuş', 'Zafer', 'Yenice'],
        'Yeşilova': ['Değirmen', 'Koyunlar']
    },
};
